version: '3'
services:
  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: dev-root
      MYSQL_USER: dev-user
      MYSQL_PASSWORD: dev-password
      MYSQL_DATABASE: ProyectoFinalDra

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
    - "5000:80"
  app:
    # Configuration for building the docker image for the service
    build: buildapp
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    